### ISSUE TITLE
`gate_recheck` comment triggers the check pipeline.

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#101]
We have a config of

```
    trigger:
      github:
        - event:
            - pr-open
            - pr-change
            - pr-reopen
        - event: pr-comment
          comment: (?i)recheck
```

on `check_github`. But in https://github.com/BonnyCI/hoist/pull/87#issuecomment-276810154 I issued a comment of `gate_recheck` and it triggered the `check_github` pipeline instead. Our regex needs work.
