### ISSUE TITLE
No breadcrumb back to test logs for successful runs

### ISSUE THREAD

**Issue by gandelman-a** [BonnyCI/projman#165]
When we run tests, anne-bonny only comments with a link to logs in the case of a failure.  Its sometimes useful to have easy access to logs from successful test runs.   Our layout currently shows:

```
    success:
      github:
        status: true
        status_url: &log_link "{{ zuul_logs_url }}/{pipeline.name}/{change.project.name}/{change.number}/{item.enqueue_time}/"
        comment: false
```
